api:
  host: 0.0.0.0
  port: 9393
  virtual-threads: false
server:
  host: 0.0.0.0
  port: 2980
docker:
  uri: "unix:///var/run/docker.sock"
  maxConnections: 100
  responseTimeout: 30
  connectionTimeout: 30