services:
    orchestrator:
        image: utfunderscore/orchestrator:1.4.5
        hostname: orchestrator
        volumes: 
            - orchestrator:/orchestrator
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 9393:9393
            - 2980:2980
        networks:
            - internal
volumes:
    orchestrator:
networks:
    internal:
        name: internal
        external: true
