services:
    orchestrator:
        image: orchestrator
        hostname: orchestrator
        stdin_open: true
        tty: true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 9393:9393
            - 2980:2980
        networks:
            - internal
networks:
    internal:
        name: internal
        external: true
