services:
  db:
    image: postgres:14.17-alpine3.21
    restart: unless-stopped
    environment:
      POSTGRES_USER: orchestrator
      POSTGRES_PASSWORD: orchestrator
      POSTGRES_DB: orchestrator
    hostname: postgres
    networks:
      - orchestrator
    volumes:
      - orchestrator-db:/var/lib/postgresql/data
volumes:
  orchestrator-db:
networks:
  orchestrator:
    external: true

